version: '3'

vars:
  # Detect OS
  UNAME_S:
    sh: uname -s
  UNAME_M:
    sh: uname -m

includes:
  install: ./tasks/install.yml
  setup: ./tasks/setup.yml
  nix: ./tasks/nix.yml
  proot: ./tasks/proot.yml
 
tasks:
  default:
    cmds:
      - task --list-all
    silent: true
