# Profile-specific starship configuration for r-shibuya
# This will be merged with the base starship configuration
[character]
format = "$symbol "
success_symbol = "[󰞷](bold dimmed fg:#3f0030)"
error_symbol = "[󰞷](bold #8f0032)"
