{ lib }:

# A binary cache in a directory on this machine, so a build survives
# `task nix:clean` and a reinstall as something to restore rather than rebuild.
#
# Only worth having where nothing else produces the same artifacts: r-shibuya is
# the one aarch64-darwin machine and droid the one aarch64-linux one, so neither
# can be served by a shared cache however good it is. Profiles that share an
# architecture use Attic instead.
#
# The caller supplies the paths and the public key because they differ by how
# the machine runs Nix -- see the two nix-cache.nix modules. The private key is
# generated on the machine and never leaves it; only its public half is
# recorded here, which is what `trusted-public-keys` needs and is not a secret.

{
  # `nix` to call, as a store path: the post-build hook runs from the daemon,
  # whose PATH is not the caller's.
  nixPackage,
  # Where the cache lives.
  cacheDir,
  # The signing key's private half, on this machine.
  keyFile,
  # Its public half, as `<name>:<base64>`.
  publicKey,
  pkgs,
}:

let
  nix = "${nixPackage}/bin/nix";

  # Pushing is not worth failing a finished build over. A cache that cannot be
  # written is either misconfigured -- which the check below catches at switch
  # time, where it belongs -- or out of disk, and breaking every build until
  # someone frees space turns a caching problem into an outage.
  pushHook = pkgs.writeShellScript "push-to-local-binary-cache" ''
    set -u
    export IFS=' '
    ${nix} copy --to "file://${cacheDir}" $OUT_PATHS \
      || echo "warning: could not push to ${cacheDir}; build kept, cache stale" >&2
  '';
in
{
  settings = {
    # Sign as we build, so nothing needs a separate signing pass before it can
    # be substituted back.
    secret-key-files = keyFile;

    # Ahead of cache.nixos.org, which advertises 40: reading a local file beats
    # a download for anything both of them have.
    extra-substituters = [ "file://${cacheDir}?priority=10" ];
    extra-trusted-public-keys = [ publicKey ];

    post-build-hook = "${pushHook}";
  };

  # Run at switch time by whichever module system owns the machine.
  #
  # The key is generated by hand once and the public half committed, so the two
  # can drift -- regenerate the key and every push is signed by something the
  # substituter no longer trusts, which shows up as the cache silently doing
  # nothing. Comparing them here turns that into a failed switch.
  checkScript = ''
    if [ ! -r "${keyFile}" ]; then
      echo "local binary cache: no signing key at ${keyFile}." >&2
      echo "  nix-store --generate-binary-cache-key <name> ${keyFile} ${keyFile}.pub" >&2
      exit 1
    fi

    have=$(${nix} key convert-secret-to-public < "${keyFile}")
    if [ "$have" != "${publicKey}" ]; then
      echo "local binary cache: the key at ${keyFile} is not the one this" >&2
      echo "configuration trusts, so nothing it signs would be substituted." >&2
      echo "  configured: ${publicKey}" >&2
      echo "  on disk:    $have" >&2
      exit 1
    fi

    mkdir -p "${cacheDir}"
    if [ ! -w "${cacheDir}" ]; then
      echo "local binary cache: ${cacheDir} is not writable." >&2
      exit 1
    fi
  '';
}
