#!/data/data/com.termux/files/usr/bin/bash
# Logseq Sync Boot Script for Termux
# Generated by task sync:logseq:schedule:termux

set -euo pipefail

export PATH=__HOME__/.nix-profile/bin:__PATH__
export LOGSEQ_LOCAL=__LOGSEQ_LOCAL__
export LOGSEQ_REMOTE=__LOGSEQ_REMOTE__
export DOTFILES_DIR=__DOTFILES_DIR__

LOG_FILE="__LOG_FILE__"
ERROR_LOG="__LOG_FILE_ERROR__"

echo "$(date '+%Y-%m-%d %H:%M:%S') - Starting logseq sync (boot)" >> "$LOG_FILE"

__DOTFILES_DIR__/bin/task sync:logseq >> "$LOG_FILE" 2>> "$ERROR_LOG"

exit 0
