# Profile-specific starship configuration for r-shibuya
# This will be merged with the base starship configuration
[character]
format = "$symbol"
success_symbol = "[󰞷](bold dimmed fg:#779922)"
error_symbol = "[󰞷](bold #8f0032)"
